// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void keyboardin_Animation(lv_obj_t * TargetObject, int delay);
void keyboardout_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Screen1_Textarea_TextArea1(lv_event_t * e);
lv_obj_t * ui_Screen1_Textarea_TextArea1;
lv_obj_t * ui_Screen1_Keyboard_Keyboard1;
lv_obj_t * ui_Screen1_Label_Label3;
void ui_event_Screen1_Button_Button4(lv_event_t * e);
lv_obj_t * ui_Screen1_Button_Button4;
lv_obj_t * ui_Screen1_Label_Label5;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Screen2_Label_Label6;
void ui_event_Screen2_Button_Button1(lv_event_t * e);
lv_obj_t * ui_Screen2_Button_Button1;
lv_obj_t * ui_Screen2_Label_Label1;
void ui_event_Screen2_Slider_Slider1(lv_event_t * e);
lv_obj_t * ui_Screen2_Slider_Slider1;
lv_obj_t * ui_Screen2_Label_Label2;
void ui_event_Screen2_Button_Button2(lv_event_t * e);
lv_obj_t * ui_Screen2_Button_Button2;
lv_obj_t * ui_Screen2_Label_Label4;
void ui_event_Screen2_Switch_Switch1(lv_event_t * e);
lv_obj_t * ui_Screen2_Switch_Switch1;
void ui_event_Screen2_Button_Button3(lv_event_t * e);
lv_obj_t * ui_Screen2_Button_Button3;
lv_obj_t * ui_Screen2_Label_Label7;
void ui_event_Screen2_Slider_Slider3(lv_event_t * e);
lv_obj_t * ui_Screen2_Slider_Slider3;
lv_obj_t * ui_Screen2_Label_Label15;
lv_obj_t * ui_Screen2_Label_Label16;
lv_obj_t * ui_Screen2_Label_Label17;
void ui_event_Screen2_Button_Button5(lv_event_t * e);
lv_obj_t * ui_Screen2_Button_Button5;
lv_obj_t * ui_Screen2_Label_Label12;


// SCREEN: ui_ExplorerScreen
void ui_ExplorerScreen_screen_init(void);
void ui_event_ExplorerScreen(lv_event_t * e);
lv_obj_t * ui_ExplorerScreen;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Screen3_Keyboard_Keyboard3;
void ui_event_Screen3_Textarea_TextAreas3t1(lv_event_t * e);
lv_obj_t * ui_Screen3_Textarea_TextAreas3t1;
void ui_event_Screen3_Textarea_TextAreas3t2(lv_event_t * e);
lv_obj_t * ui_Screen3_Textarea_TextAreas3t2;
void ui_event_Screen3_Textarea_TextAreas3t3(lv_event_t * e);
lv_obj_t * ui_Screen3_Textarea_TextAreas3t3;
void ui_event_Screen3_Button_Button6(lv_event_t * e);
lv_obj_t * ui_Screen3_Button_Button6;
lv_obj_t * ui_Screen3_Label_Label9;
void ui_event_Screen3_Button_Button7(lv_event_t * e);
lv_obj_t * ui_Screen3_Button_Button7;
lv_obj_t * ui_Screen3_Label_Label10;
void ui_event_Screen3_Button_Button8(lv_event_t * e);
lv_obj_t * ui_Screen3_Button_Button8;
lv_obj_t * ui_Screen3_Label_Label11;
lv_obj_t * ui_Screen3_Label_Label8;
lv_obj_t * ui_Screen3_Label_Label13;
lv_obj_t * ui_Screen3_Label_Label14;
lv_obj_t * ui_Startevents____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void keyboardin_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 350, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void keyboardout_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, 300);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1_Textarea_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Screen1_Keyboard_Keyboard1,  ui_Screen1_Textarea_TextArea1);
        keyboardin_Animation(ui_Screen1_Keyboard_Keyboard1, 0);
        _ui_flag_modify(ui_Screen1_Keyboard_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Screen1_Button_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        CheckPasswd(e);
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Timer_Create(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        Timer_Delete(e);
    }
}
void ui_event_Screen2_Button_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen2_Slider_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Slider1_proc(e);
    }
}
void ui_event_Screen2_Button_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ExplorerScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ExplorerScreen_screen_init);
    }
}
void ui_event_Screen2_Switch_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Switch_mp3_changed(e);
    }
}
void ui_event_Screen2_Button_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_Screen2_Slider_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Slider3_proc(e);
    }
}
void ui_event_Screen2_Button_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        button5_clicked_proc(e);
    }
}
void ui_event_ExplorerScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ExplorerScreenLoaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ExplorerScreenUnLoaded(e);
    }
}
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        screen3loadedfunc(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        screen3unloadedfunc(e);
    }
}
void ui_event_Screen3_Textarea_TextAreas3t1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Screen3_Keyboard_Keyboard3,  ui_Screen3_Textarea_TextAreas3t1);
    }
}
void ui_event_Screen3_Textarea_TextAreas3t2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Screen3_Keyboard_Keyboard3,  ui_Screen3_Textarea_TextAreas3t2);
    }
}
void ui_event_Screen3_Textarea_TextAreas3t3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Screen3_Keyboard_Keyboard3,  ui_Screen3_Textarea_TextAreas3t3);
    }
}
void ui_event_Screen3_Button_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        changepasswordvisible(e);
    }
}
void ui_event_Screen3_Button_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        passwordchange(e);
    }
}
void ui_event_Screen3_Button_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_ExplorerScreen_screen_init();
    ui_Screen3_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
