// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Screen1_Textarea_TextArea1(lv_event_t * e);
lv_obj_t * ui_Screen1_Textarea_TextArea1;
lv_obj_t * ui_Screen1_Keyboard_Keyboard1;
lv_obj_t * ui_Screen1_Label_Label3;
void ui_event_Screen1_Button_Button4(lv_event_t * e);
lv_obj_t * ui_Screen1_Button_Button4;
lv_obj_t * ui_Screen1_Label_Label5;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Screen2_Label_Label6;
void ui_event_Screen2_Button_Button1(lv_event_t * e);
lv_obj_t * ui_Screen2_Button_Button1;
lv_obj_t * ui_Screen2_Label_Label1;
void ui_event_Screen2_Slider_Slider1(lv_event_t * e);
lv_obj_t * ui_Screen2_Slider_Slider1;
lv_obj_t * ui_Screen2_Label_Label2;
void ui_event_Screen2_Button_Button2(lv_event_t * e);
lv_obj_t * ui_Screen2_Button_Button2;
lv_obj_t * ui_Screen2_Label_Label4;
void ui_event_Screen2_Switch_Switch1(lv_event_t * e);
lv_obj_t * ui_Screen2_Switch_Switch1;


// SCREEN: ui_ExplorerScreen
void ui_ExplorerScreen_screen_init(void);
void ui_event_ExplorerScreen(lv_event_t * e);
lv_obj_t * ui_ExplorerScreen;
lv_obj_t * ui_Startevents____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1_Textarea_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Screen1_Keyboard_Keyboard1,  ui_Screen1_Textarea_TextArea1);
    }
}
void ui_event_Screen1_Button_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        CheckPasswd(e);
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Timer_Create(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        Timer_Delete(e);
    }
}
void ui_event_Screen2_Button_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Screen2_Slider_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Slider1_proc(e);
    }
}
void ui_event_Screen2_Button_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ExplorerScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ExplorerScreen_screen_init);
    }
}
void ui_event_Screen2_Switch_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Switch_mp3_changed(e);
    }
}
void ui_event_ExplorerScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ExplorerScreenLoaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ExplorerScreenUnLoaded(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_ExplorerScreen_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
