// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void keyboardin_Animation(lv_obj_t * TargetObject, int delay);
void keyboardout_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Screen1_Textarea_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Textarea_TextArea1;
extern lv_obj_t * ui_Screen1_Keyboard_Keyboard1;
extern lv_obj_t * ui_Screen1_Label_Label3;
void ui_event_Screen1_Button_Button4(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Button_Button4;
extern lv_obj_t * ui_Screen1_Label_Label5;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Screen2_Label_Label6;
void ui_event_Screen2_Button_Button1(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button_Button1;
extern lv_obj_t * ui_Screen2_Label_Label1;
void ui_event_Screen2_Slider_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Slider_Slider1;
extern lv_obj_t * ui_Screen2_Label_Label2;
void ui_event_Screen2_Button_Button2(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button_Button2;
extern lv_obj_t * ui_Screen2_Label_Label4;
void ui_event_Screen2_Switch_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Switch_Switch1;
void ui_event_Screen2_Button_Button3(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button_Button3;
extern lv_obj_t * ui_Screen2_Label_Label7;
void ui_event_Screen2_Slider_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Slider_Slider3;
extern lv_obj_t * ui_Screen2_Label_Label15;
extern lv_obj_t * ui_Screen2_Label_Label16;
extern lv_obj_t * ui_Screen2_Label_Label17;
void ui_event_Screen2_Button_Button5(lv_event_t * e);
extern lv_obj_t * ui_Screen2_Button_Button5;
extern lv_obj_t * ui_Screen2_Label_Label12;
// SCREEN: ui_ExplorerScreen
void ui_ExplorerScreen_screen_init(void);
void ui_event_ExplorerScreen(lv_event_t * e);
extern lv_obj_t * ui_ExplorerScreen;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Screen3_Keyboard_Keyboard3;
void ui_event_Screen3_Textarea_TextAreas3t1(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Textarea_TextAreas3t1;
void ui_event_Screen3_Textarea_TextAreas3t2(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Textarea_TextAreas3t2;
void ui_event_Screen3_Textarea_TextAreas3t3(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Textarea_TextAreas3t3;
void ui_event_Screen3_Button_Button6(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Button_Button6;
extern lv_obj_t * ui_Screen3_Label_Label9;
void ui_event_Screen3_Button_Button7(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Button_Button7;
extern lv_obj_t * ui_Screen3_Label_Label10;
void ui_event_Screen3_Button_Button8(lv_event_t * e);
extern lv_obj_t * ui_Screen3_Button_Button8;
extern lv_obj_t * ui_Screen3_Label_Label11;
extern lv_obj_t * ui_Screen3_Label_Label8;
extern lv_obj_t * ui_Screen3_Label_Label13;
extern lv_obj_t * ui_Screen3_Label_Label14;
extern lv_obj_t * ui_Startevents____initial_actions0;





LV_FONT_DECLARE(ui_font_ysFont);
LV_FONT_DECLARE(ui_font_ysFont40);
LV_FONT_DECLARE(ui_font_ys30);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
