// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void CheckPasswd(lv_event_t * e);
void Timer_Create(lv_event_t * e);
void Timer_Delete(lv_event_t * e);
void Slider1_proc(lv_event_t * e);
void Switch_mp3_changed(lv_event_t * e);
void ExplorerScreenLoaded(lv_event_t * e);
void ExplorerScreenUnLoaded(lv_event_t * e);
void screen3loadedfunc(lv_event_t * e);
void screen3unloadedfunc(lv_event_t * e);
void changepasswordvisible(lv_event_t * e);
void passwordchange(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
