// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "MP3IOT.h"
#include "examples/others/file_explorer/lv_example_file_explorer.h"
#include "ff.h"
#include "lvgl.h"
#include "rtc.h"
#include "src/core/lv_obj.h"
#include "src/core/lv_obj_event.h"
#include "src/core/lv_obj_pos.h"
#include "src/core/lv_obj_style.h"
#include "src/core/lv_obj_style_gen.h"
#include "src/core/lv_obj_tree.h"
#include "src/font/lv_font.h"
#include "src/misc/lv_event.h"
#include "src/misc/lv_types.h"
#include "src/others/file_explorer/lv_file_explorer.h"
#include "src/widgets/textarea/lv_textarea.h"
#include "stm32f4xx.h"
#include "stm32f4xx_hal_rtc.h"
#include "ui.h"
#include "main.h"
#include "ui_helpers.h"
#include <stdbool.h>
#include <stdio.h>
#include <sys/_intsup.h>
#include "GNSS.h"

void button1_clicked(lv_event_t *e) {
    // Your code here
    HAL_GPIO_TogglePin(LED1_GPIO_Port, LED1_Pin);
}

void CheckPasswd(lv_event_t *e) {
// Your code here
#define PASSWORD_NOCHECK
#ifdef PASSWORD_NOCHECK
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    return;
#undef PASSWORD_NOCHECK
#endif
    const char *pwdtmp = lv_textarea_get_text(ui_Screen1_Textarea_TextArea1);

    if (lv_strcmp("password", pwdtmp) == 0) {
        lv_textarea_set_text(ui_Screen1_Textarea_TextArea1, ""); // 清空密码框
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

static void timelabel_update_timer(lv_timer_t *timer) {
    // Your code here
    // printf("label updater running\n");
    char tmp[60];
    RTC_TimeTypeDef sTime;
    RTC_DateTypeDef sDate;
    HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN); // 不读日期会导致时间被锁定
    sprintf(tmp, "%04d-%02d-%02d %02d:%02d:%02d", sDate.Year + 2000, sDate.Month, sDate.Date, sTime.Hours, sTime.Minutes, sTime.Seconds);
    lv_label_set_text(ui_Screen2_Label_Label6, tmp);

    // GNSS
    sprintf(tmp, "GNSS:\n\
longitude: %6.2f%c\n\
latitude:%6.2f%c\n\
    ",
            longitude, longitude_dir, latitude, latitude_dir);
    lv_label_set_text(ui_Screen2_Label_Label2, tmp);
}
static lv_timer_t *timelabel_update_timer_ptr;
void Timer_Create(lv_event_t *e) {
    // Your code here
    timelabel_update_timer_ptr = lv_timer_create(timelabel_update_timer, 100, NULL);
}

void Timer_Delete(lv_event_t *e) {
    // Your code here
    lv_timer_delete(timelabel_update_timer_ptr);
}

void Slider1_proc(lv_event_t *e) {
    // Your code here
    int val = lv_slider_get_value(ui_Screen2_Slider_Slider1);
    // Adjust PWM duty cycle of TIM10 channel 1
    TIM10->CCR1 = val * 10;
}

static lv_obj_t *sudoer_ui_Explorer;
static lv_obj_t *sudoer_ui_ExplorerWindow;
static lv_obj_t *sudoer_ui_ExplorerWindow_CloseButton;

static void ExplorerWindowClose(lv_event_t *e) {
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
}
static lv_obj_t *sudoer_ui_image_window;
static lv_obj_t *sudoer_ui_image;
static void ImageWindowClose(lv_event_t *e) {
    lv_obj_delete(sudoer_ui_image_window);
    sudoer_ui_image_window = NULL;
}
static void Explorer_file_selected_handler(lv_event_t *e) {
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (code == LV_EVENT_VALUE_CHANGED) {
        const char *cur_path = lv_file_explorer_get_current_path(obj);
        const char *sel_fn = lv_file_explorer_get_selected_file_name(obj);
        // 如果以jpg或bmp结尾
        uint16_t len = lv_strlen(sel_fn);
        if (len > 4 && (lv_strcmp(sel_fn + len - 4, ".jpg") == 0 || lv_strcmp(sel_fn + len - 4, ".bmp") == 0)) {
            char path[256];
            lv_strcpy(path, cur_path);
            lv_strcpy(path + lv_strlen(cur_path) - 1, sel_fn);
            printf("open file %s\n", path);

            sudoer_ui_image_window = lv_win_create(ui_ExplorerScreen);
            lv_obj_set_pos(sudoer_ui_ExplorerWindow, 0, 0);
            char title[256];
            sprintf(title, "图片读取:%s", sel_fn);
            lv_win_add_title(sudoer_ui_image_window, title);
            lv_obj_t *button = lv_win_add_button(sudoer_ui_image_window, LV_SYMBOL_CLOSE, 50);
            lv_obj_add_event_cb(button, ImageWindowClose, LV_EVENT_CLICKED, NULL);
            lv_obj_set_style_text_font(button, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
            sudoer_ui_image = lv_image_create(sudoer_ui_image_window);
            lv_image_set_src(sudoer_ui_image, path);
        }
        // 如果以txt结尾
        else if (len > 4 && lv_strcmp(sel_fn + len - 4, ".txt") == 0) {
            char path[256];
            lv_strcpy(path, cur_path);
            lv_strcpy(path + lv_strlen(cur_path) - 1, sel_fn);
            printf("open file %s\n", path);
            FIL file;
            FRESULT res = f_open(&file, path, FA_READ);
            if (res == FR_OK) {
                const int max_file_len = 10240;
                uint8_t *buf = lv_malloc(max_file_len);
                // 先判断文件长度
                f_lseek(&file, 0);
                UINT filesize = f_size(&file);
                if (filesize > 10240) {
                    f_lseek(&file, filesize - max_file_len);
                }
                UINT br;
                f_read(&file, buf, max_file_len, &br);
                buf[br] = 0;
                sudoer_ui_image_window = lv_win_create(ui_ExplorerScreen);
                char title[256];
                sprintf(title, "txt文件读取:%s", sel_fn);
                lv_win_add_title(sudoer_ui_image_window, title);
                lv_obj_set_pos(sudoer_ui_image_window, 0, 0);
                lv_obj_t *button = lv_win_add_button(sudoer_ui_image_window, LV_SYMBOL_CLOSE, 50);
                lv_obj_add_event_cb(button, ImageWindowClose, LV_EVENT_CLICKED, NULL);
                lv_obj_set_style_text_font(button, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
                lv_obj_set_style_text_font(sudoer_ui_image_window, &ui_font_ysFont, LV_PART_MAIN | LV_STATE_DEFAULT);
                // 添加文本框
                lv_obj_t *textarea = lv_textarea_create(sudoer_ui_image_window);
                lv_textarea_set_text(textarea, (const char *)buf);
                lv_obj_set_size(textarea, 800, 400);
                lv_obj_set_style_text_font(textarea, &ui_font_ysFont, LV_PART_MAIN | LV_STATE_DEFAULT);
                // 将光标设置回开头
                lv_textarea_set_cursor_pos(textarea, 0);
                lv_textarea_set_cursor_click_pos(textarea, true);
                lv_free(buf);
            }
        }
    }
}
void ExplorerScreenLoaded(lv_event_t *e) {
    // Your code here
    sudoer_ui_ExplorerWindow = lv_win_create(ui_ExplorerScreen);
    lv_win_add_title(sudoer_ui_ExplorerWindow, "Explorer");
    lv_obj_set_style_text_font(sudoer_ui_ExplorerWindow, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(sudoer_ui_ExplorerWindow, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    sudoer_ui_ExplorerWindow_CloseButton = lv_win_add_button(sudoer_ui_ExplorerWindow, LV_SYMBOL_CLOSE, 50);
    lv_obj_add_event_cb(sudoer_ui_ExplorerWindow_CloseButton, ExplorerWindowClose, LV_EVENT_CLICKED, NULL);
    sudoer_ui_Explorer = lv_file_explorer_create(sudoer_ui_ExplorerWindow);
    lv_file_explorer_set_sort(sudoer_ui_Explorer, LV_EXPLORER_SORT_NONE);
    lv_file_explorer_open_dir(sudoer_ui_Explorer, "0:/");
    lv_obj_set_size(sudoer_ui_Explorer, 800, 400);
    lv_obj_add_event_cb(sudoer_ui_Explorer, Explorer_file_selected_handler, LV_EVENT_VALUE_CHANGED, NULL);
}

void ExplorerScreenUnLoaded(lv_event_t *e) {
    // Your code here
    lv_obj_delete(sudoer_ui_ExplorerWindow);
}

void Switch_mp3_changed(lv_event_t *e) {
    // Your code here
    if (lv_obj_has_state(ui_Screen2_Switch_Switch1, LV_STATE_CHECKED)) {
        mp3_play();
    } else {
        mp3_stop();
    }
}

void screen3loadedfunc(lv_event_t *e) {
    // Your code here
}

void screen3unloadedfunc(lv_event_t *e) {
    // Your code here
}
