// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "rtc.h"
#include "stdlib/lv_string.h"
#include "stm32f4xx.h"
#include "stm32f4xx_hal_rtc.h"
#include "ui.h"
#include "main.h"
#include "ui_helpers.h"
#include <stdio.h>
#include "GNSS.h"
#include "widgets/textarea/lv_textarea.h"

void button1_clicked(lv_event_t *e) {
    // Your code here
    HAL_GPIO_TogglePin(LED1_GPIO_Port, LED1_Pin);
}

void CheckPasswd(lv_event_t *e) {
// Your code here
#define PASSWORD_NOCHECK
#ifdef PASSWORD_NOCHECK
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    return;
#undef PASSWORD_NOCHECK
#endif
    const char *pwdtmp = lv_textarea_get_text(ui_Screen1_Textarea_TextArea1);

    if (lv_strcmp("password", pwdtmp) == 0) {
        lv_textarea_set_text(ui_Screen1_Textarea_TextArea1,"");//清空密码框
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

static void timelabel_update_timer(lv_timer_t *timer) {
    // Your code here
    // printf("label updater running\n");
    char tmp[60];
    RTC_TimeTypeDef sTime;
    RTC_DateTypeDef sDate;
    HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN); // 不读日期会导致时间被锁定
    sprintf(tmp, "%04d-%02d-%02d %02d:%02d:%02d", sDate.Year + 2000, sDate.Month, sDate.Date, sTime.Hours, sTime.Minutes, sTime.Seconds);
    lv_label_set_text(ui_Screen2_Label_Label6, tmp);

    // GNSS
    sprintf(tmp, "GNSS:\n\
longitude: %6.2f%c\n\
latitude:%6.2f%c\n\
    ",
            longitude, longitude_dir, latitude, latitude_dir);
    lv_label_set_text(ui_Screen2_Label_Label2, tmp);
}
static lv_timer_t *timelabel_update_timer_ptr;
void Timer_Create(lv_event_t *e) {
    // Your code here
    timelabel_update_timer_ptr = lv_timer_create(timelabel_update_timer, 100, NULL);
}

void Timer_Delete(lv_event_t *e) {
    // Your code here
    lv_timer_delete(timelabel_update_timer_ptr);
}

void Slider1_proc(lv_event_t *e) {
    // Your code here
    int val = lv_slider_get_value(ui_Screen2_Slider_Slider1);
    // Adjust PWM duty cycle of TIM10 channel 1
    TIM10->CCR1 = val * 10;
}

void ExplorerScreenLoaded(lv_event_t * e)
{
	// Your code here
}

void ExplorerScreenUnLoaded(lv_event_t * e)
{
	// Your code here
}
