// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xCBFCD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Label_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label_Label6, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Screen2_Label_Label6, "TIME:");
    lv_obj_set_style_text_color(ui_Screen2_Label_Label6, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen2_Label_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2_Label_Label6, &ui_font_ysFont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Button_Button1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Button_Button1, 100);
    lv_obj_set_height(ui_Screen2_Button_Button1, 50);
    lv_obj_set_x(ui_Screen2_Button_Button1, 345);
    lv_obj_set_y(ui_Screen2_Button_Button1, -209);
    lv_obj_set_align(ui_Screen2_Button_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Button_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Screen2_Button_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2_Label_Label1 = lv_label_create(ui_Screen2_Button_Button1);
    lv_obj_set_width(ui_Screen2_Label_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2_Label_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label_Label1, "LOCK\nDEVICE");
    lv_obj_set_style_text_color(ui_Screen2_Label_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen2_Label_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen2_Label_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2_Label_Label1, &ui_font_ysFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2_Button_Button1, ui_event_Screen2_Button_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
