// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Textarea_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Textarea_TextArea1, 655);
    lv_obj_set_height(ui_Screen1_Textarea_TextArea1, LV_SIZE_CONTENT);    /// 140
    lv_obj_set_x(ui_Screen1_Textarea_TextArea1, 27);
    lv_obj_set_y(ui_Screen1_Textarea_TextArea1, 116);
    lv_textarea_set_placeholder_text(ui_Screen1_Textarea_TextArea1, "密码");
    lv_textarea_set_one_line(ui_Screen1_Textarea_TextArea1, true);
    lv_textarea_set_password_mode(ui_Screen1_Textarea_TextArea1, true);
    lv_obj_set_style_text_font(ui_Screen1_Textarea_TextArea1, &ui_font_ysFont, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Screen1_Keyboard_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Keyboard_Keyboard1, 800);
    lv_obj_set_height(ui_Screen1_Keyboard_Keyboard1, 280);
    lv_obj_set_x(ui_Screen1_Keyboard_Keyboard1, 0);
    lv_obj_set_y(ui_Screen1_Keyboard_Keyboard1, 280);
    lv_obj_add_flag(ui_Screen1_Keyboard_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Keyboard_Keyboard1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Keyboard_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_Keyboard_Keyboard1, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Keyboard_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Screen1_Keyboard_Keyboard1, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Keyboard_Keyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Keyboard_Keyboard1, &lv_font_montserrat_18, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Screen1_Label_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Label3, -257);
    lv_obj_set_y(ui_Screen1_Label_Label3, -161);
    lv_obj_set_align(ui_Screen1_Label_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Label3, "请输入密码：");
    lv_obj_set_style_text_color(ui_Screen1_Label_Label3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_Label3, &ui_font_ysFont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Button_Button4 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Button_Button4, 100);
    lv_obj_set_height(ui_Screen1_Button_Button4, 50);
    lv_obj_set_x(ui_Screen1_Button_Button4, 347);
    lv_obj_set_y(ui_Screen1_Button_Button4, -101);
    lv_obj_set_align(ui_Screen1_Button_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Button_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Screen1_Button_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Button_Button4, lv_color_hex(0xD04F97), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Button_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Label5 = lv_label_create(ui_Screen1_Button_Button4);
    lv_obj_set_width(ui_Screen1_Label_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Label5, "提交");
    lv_obj_set_style_text_color(ui_Screen1_Label_Label5, lv_color_hex(0x2000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_Label5, &ui_font_ysFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1_Textarea_TextArea1, ui_event_Screen1_Textarea_TextArea1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Screen1_Keyboard_Keyboard1, ui_Screen1_Textarea_TextArea1);
    lv_obj_add_event_cb(ui_Screen1_Button_Button4, ui_event_Screen1_Button_Button4, LV_EVENT_ALL, NULL);

}
